### ISSUE TITLE
feat: Support `federated plugin` template generateion

### ISSUE THREAD

**Issue by Sunbreak** [woodemi/quick_flutter.brick#2]
**Description**

Support `federated plugin` template generateion

**Requirements**

* [x] #8
* [x] #9
* [x] #10
* [x] #14
* [x] #17
* [x] #20

**Comment by Sunbreak** [comment]
Related tasks are completed

@mzdm, anything else am I missing?

**Comment by mzdm** [comment]
> Related tasks are completed
> 
> @mzdm, anything else am I missing?

That was fast, thanks!

**Comment by Sunbreak** [comment]
There is another discussion in #22
