### ISSUE TITLE
Inconsistent federation structure

### ISSUE THREAD

**Issue by stuartmorgan-g** [woodemi/quick_flutter.brick#22]
The federated plugin here has every implementation in its own package, except that iOS and Android are inline in the app-facing package.

The only reason I'm aware of for a plugin to have that structure is when the plugin predates federation, was minimally adapted to federation (by extracting a platform interface, but not moving the existing iOS and Android implementations), and then new platforms were added following the federated model. Recreating that specific legacy situation in a template for new plugins seems confusing.

**Comment by Sunbreak** [comment]
> Recreating that specific legacy situation in a template for new plugins seems confusing.

So what is a fresh federated structure supposed to be?

- Choice A: all implementations inline in the app-facing package

```sh
$ $ mason make quick_flutter --project myplugin
...
$ ls myplugin/
CHANGELOG.md	README.md	example		lib		macos		pubspec.yaml	windows
LICENSE		android		ios		linux		pubspec.lock	test
```

- Choice B: all implementations are in their own federated package

```
$ mason make quick_flutter_federated_plugin
...
$ ls fedplugin/
fedplugin			fedplugin_ios			fedplugin_macos			fedplugin_web
fedplugin_android		fedplugin_linux			fedplugin_platform_interface	fedplugin_windows
```

**Comment by Piero512** [comment]
To add to this discussion, last I checked, the app-facing package used to NEED at the very least a NotImplemented plugin implementation for iOS or, otherwise, your plugin blocks pod install

**Comment by Sunbreak** [comment]
> To add to this discussion, last I checked, the app-facing package used to NEED at the very least a NotImplemented plugin implementation for iOS or, otherwise, your plugin blocks pod install

- [Allow plugins to not support Android](https://github.com/flutter/flutter/issues/39657) closed at Apr 10, 2020
- [Allow plugins to not support iOS](https://github.com/flutter/flutter/issues/39659) closed at Jun 12, 2020
- [Allow plugins not to support macOS](https://github.com/flutter/flutter/issues/46618) closed at Dec 18, 2020

**Comment by stuartmorgan-g** [comment]
> So what is a fresh federated structure supposed to be?

There is no "supposed to"; there isn't one right way to structure it, nor are the two options you have the only ones. However, just because there's no one right way, that doesn't mean all possible arrangements are equally good in every situation; as with structuring/organizing anything, it's useful to have a clear reason for the chosen structure.

The structure you have here isn't wrong per se, but per my comment above the only reason for it I know of in the abstract doesn't apply to new plugins, making it an odd default choice.

> * Choice A: all implementations inline in the app-facing package

This is certainly a reasonable option, although I would strongly recommend putting the platform interface in a separate package. If you don't, endorsing a separate implementation later becomes problematic due to circular references.

One potential downside of this approach is that the plugin author may not notice design issues that would make writing separate implementations (if someone else wants to add a new platform as a new package) harder. E.g., accidentally putting code that all implementations would need in the app-facing package rather than the platform interface package.

> * Choice B: all implementations are in their own federated package

This is also a reasonable default option.

Other options may make more sense in specific situations:
* sometimes iOS and macOS plugin implementations can share the same code with very minor ifdefs, so those two implementations could need to share a package.
* joint authors might want to split implementations into packages (potentially in separate repos) based on the platforms they will each be supporting.
* a subset of platforms might all need the same API extensions, making it convenient to put those in one package.
* a subset of platforms might all have such similar platform API structure that it makes sense for them to share the same method channel as an implementation detail, so might be grouped based on that.

But in each case, the choice is made for a reason.

**Comment by Sunbreak** [comment]
mason is quite simple now and is not able to support so much structures in a same repo

I'm  considering extract `quick_flutter_federated` and `quick_flutter_federated_legacy` for `Choice A` and the predate structure

**Comment by stuartmorgan-g** [comment]
> mason is quite simple now and is not able to support so much structures in a same repo

I wasn't suggesting you should support all of those options. My point was that while many structures are possible, those that don't have a consistent structure would be that way *for a specific reason*. A generic template by definition doesn't have a specific reason, so it doesn't really make sense for it to do something inconsistent.

> and `quick_flutter_federated_legacy` for [...] the predate structure

Why? What possible reason is there to have a template for new plugins that replicates a structure that has no relevance for new plugins?

**Comment by Sunbreak** [comment]
> Why? What possible reason is there to have a template for new plugins that replicates a structure that has no relevance for new plugins?

I suppose most federated developer are familiar with the predate structure. And quite a lot related shell/batch are running: https://github.com/woodemi/quick_blue/blob/master/.github/workflows/main.yml

**Comment by stuartmorgan-g** [comment]
It sounds like you are committed to encouraging developers of new plugins to cargo-cult this hybrid structure from partially-migrated existing plugins.

I think that's unfortunate, since it will simply perpetuate the misunderstanding people have that it is required, or even preferred for some reason, but obviously you can structure your project however you want to.

**Comment by Sunbreak** [comment]
> mason is quite simple now and is not able to support so much structures in a same repo
> 
> I'm considering extract `quick_flutter_federated` and `quick_flutter_federated_legacy` for `Choice A` and the predate structure

0.4.0 released with `quick_flutter_federated` and `quick_flutter_federated_legacy`

https://github.com/woodemi/quick_flutter.brick/tree/0.4.0
