### ISSUE TITLE
Errors for includes and other things

### ISSUE THREAD

**Issue by sgehrman** [woodemi/quick_flutter.brick#28]
Trying to create a plugin that doesn't have errors everywhere.  I used this and the cc and .h files still have errors.  I'm on linux.

I tried for hours to get a simple plugin to open up so I can edit linux files and get full intellisense.   Nothing I did worked. I tried quick_flutter and the normal flutter and both failed.

 I can get the example apps linux folder to work, but I need to be able to edit the linux plugin.  There are zero instructions on how to get this working.  Any ideas?

**Comment by Sunbreak** [comment]
> Trying to create a plugin that doesn't have errors everywhere. I used this and the cc and .h files still have errors. I'm on linux.

Not sure what `still have errors` means. Could you upload some log or screenshot?

I test app/plugin/federated/federated_legacy and each compiles successufly

**Comment by sgehrman** [comment]
They compile, but I want to edit my linux c++ code in my plugin and get auto complete and syntax checking, but I can't get that working.  I'm using VSCode.

**Comment by Sunbreak** [comment]
It is related to the C/C++ extension of VS Code I think.

When creating with `flutter create -t plugin --platforms=linux myplugin` and opening the project with VS Code, you get those "errors" in cc and .h files within the editor as well

![image](https://user-images.githubusercontent.com/7928961/131273186-eb00116b-d295-4f4e-a23f-7c3c3448c692.png)

https://medium.com/flutter-community/flutter-linux-plugin-development-setup-e30f504baadd this post may help

**Comment by sgehrman** [comment]
I kind of figured it out.  It's very tricky to get right.  C/C++ Edit Configuration on the VSCode project that contains all the plugins seems to work.

**Comment by Sunbreak** [comment]
> I kind of figured it out. It's very tricky to get right. C/C++ Edit Configuration on the VSCode project that contains all the plugins seems to work.

Could you share some experience? I'd like to add to README

**Comment by sgehrman** [comment]
OK, I'll try to setup a simple test project.
